config/routes.rb
Rails.application.routes.draw do
  resources :venda_produtos

  resources :produtos

  resources :vendas

  resources :funcionarios

  resources :clientes

end

app/models/produto.rb
class Produto < ActiveRecord::Base
	has_many :venda_produtos
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :marca, :descricao, :montadora, :modelo, :motor, :complemento, :ano, :codigodebarra, :estoque, :valor)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= simple_form_for(@produto) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :marca %>
    <%= f.input :descricao %>
    <%= f.input :montadora %>
    <%= f.input :modelo %>
    <%= f.input :motor %>
    <%= f.input :complemento %>
    <%= f.input :ano %>
    <%= f.input :codigodebarra %>
    <%= f.input :estoque %>
    <%= f.input :valor %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<h1>Listing produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Marca</th>
      <th>Descricao</th>
      <th>Montadora</th>
      <th>Modelo</th>
      <th>Motor</th>
      <th>Complemento</th>
      <th>Ano</th>
      <th>Codigodebarra</th>
      <th>Estoque</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.marca %></td>
        <td><%= produto.descricao %></td>
        <td><%= produto.montadora %></td>
        <td><%= produto.modelo %></td>
        <td><%= produto.motor %></td>
        <td><%= produto.complemento %></td>
        <td><%= produto.ano %></td>
        <td><%= produto.codigodebarra %></td>
        <td><%= produto.estoque %></td>
        <td><%= produto.valor %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= render 'form' %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @produto.marca %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<p>
  <strong>Montadora:</strong>
  <%= @produto.montadora %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @produto.modelo %>
</p>

<p>
  <strong>Motor:</strong>
  <%= @produto.motor %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @produto.complemento %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @produto.ano %>
</p>

<p>
  <strong>Codigodebarra:</strong>
  <%= @produto.codigodebarra %>
</p>

<p>
  <strong>Estoque:</strong>
  <%= @produto.estoque %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @produto.valor %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>