config/routes.rb
Rails.application.routes.draw do
  resources :venda_produtos

  resources :produtos

  resources :vendas

  resources :funcionarios

  resources :clientes

end

app/models/venda.rb
class Venda < ActiveRecord::Base
	has_many :venda_produtos
	belongs_to :cliente
	belongs_to :funcionario
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :set_venda, only: [:show, :edit, :update, :destroy]

  # GET /vendas
  # GET /vendas.json
  def index
    @vendas = Venda.all
  end

  # GET /vendas/1
  # GET /vendas/1.json
  def show
  end

  # GET /vendas/new
  def new
    @venda = Venda.new
  end

  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas
  # POST /vendas.json
  def create
    @venda = Venda.new(venda_params)

    respond_to do |format|
      if @venda.save
        format.html { redirect_to @venda, notice: 'Venda was successfully created.' }
        format.json { render :show, status: :created, location: @venda }
      else
        format.html { render :new }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas/1
  # PATCH/PUT /vendas/1.json
  def update
    respond_to do |format|
      if @venda.update(venda_params)
        format.html { redirect_to @venda, notice: 'Venda was successfully updated.' }
        format.json { render :show, status: :ok, location: @venda }
      else
        format.html { render :edit }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas/1
  # DELETE /vendas/1.json
  def destroy
    @venda.destroy
    respond_to do |format|
      format.html { redirect_to vendas_url, notice: 'Venda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venda
      @venda = Venda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venda_params
      params.require(:venda).permit(:valor, :data, :funcionario_id, :cliente_id)
    end
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/vendas/_form.html.erb
<%= simple_form_for(@venda) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :valor %>
    <%= f.input :data %>
    <%= f.input :funcionario_id %>
    <%= f.input :cliente_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vendas/edit.html.erb
<h1>Editing venda</h1>

<%= render 'form' %>

<%= link_to 'Show', @venda %> |
<%= link_to 'Back', vendas_path %>

app/views/vendas/index.html.erb
<h1>Listing vendas</h1>

<table>
  <thead>
    <tr>
      <th>Valor</th>
      <th>Data</th>
      <th>Funcionario</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendas.each do |venda| %>
      <tr>
        <td><%= venda.valor %></td>
        <td><%= venda.data %></td>
        <td><%= venda.funcionario_id %></td>
        <td><%= venda.cliente_id %></td>
        <td><%= link_to 'Show', venda %></td>
        <td><%= link_to 'Edit', edit_venda_path(venda) %></td>
        <td><%= link_to 'Destroy', venda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venda', new_venda_path %>

app/views/vendas/new.html.erb
<h1>New venda</h1>

<%= render 'form' %>

<%= link_to 'Back', vendas_path %>

app/views/vendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valor:</strong>
  <%= @venda.valor %>
</p>

<p>
  <strong>Data:</strong>
  <%= @venda.data %>
</p>

<p>
  <strong>Funcionario:</strong>
  <%= @venda.funcionario_id %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @venda.cliente_id %>
</p>

<%= link_to 'Edit', edit_venda_path(@venda) %> |
<%= link_to 'Back', vendas_path %>