config/routes.rb
Rails.application.routes.draw do
  resources :venda_produtos

  resources :produtos

  resources :vendas

  resources :funcionarios

  resources :clientes

end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
	has_many :vendas
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :telefone, :endereco, :salario)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= simple_form_for(@funcionario) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :cpf %>
    <%= f.input :telefone %>
    <%= f.input :endereco %>
    <%= f.input :salario %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editing funcionario</h1>

<%= render 'form' %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<h1>Listing funcionarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Telefone</th>
      <th>Endereco</th>
      <th>Salario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.cpf %></td>
        <td><%= funcionario.telefone %></td>
        <td><%= funcionario.endereco %></td>
        <td><%= funcionario.salario %></td>
        <td><%= link_to 'Show', funcionario %></td>
        <td><%= link_to 'Edit', edit_funcionario_path(funcionario) %></td>
        <td><%= link_to 'Destroy', funcionario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcionario', new_funcionario_path %>

app/views/funcionarios/new.html.erb
<h1>New funcionario</h1>

<%= render 'form' %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @funcionario.cpf %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @funcionario.telefone %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @funcionario.endereco %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @funcionario.salario %>
</p>

<%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Back', funcionarios_path %>